package:
  name: pyArcObjects
  version: "1.2.0"

source:
  git_rev: v1.2.0
  git_url: https://github.com/canopusgeo/pyArcObjects.git

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - pyArcObjects

about:
  home: https://github.com/canopusgeo/pyArcObjects
  license: GNUv2
  license_file: LICENSE
